### ISSUE TITLE
No license? 

### ISSUE THREAD

**Issue by santrancisco** [davidmcclure/humanist#1]
Hi David,

I really love the UI work you did  for this project and actually used it in a personal project for myself to graph network traffic and would love to opensource it for others to use. Unfortunately you didn't attach any License to the project so I'm unsure if you would be comfortable with me sharing/releasing it. Could you please let me know if this is ok and if possible, can you attach a license to the project? :)

Kind regards,
San

**Comment by davidmcclure** [comment]
Hey San, I just put an MIT license on it - certainly feel free to use this however! Cheers.

**Comment by santrancisco** [comment]
Thanks so much for adding the license :) Just thought you might be interested in what i used it for here  https://github.com/santrancisco/graphflowlog .

The demo for that is here: https://sampleflowlog.surge.sh/

I did spend a fair bit of time trying to find a sensible  d3 graphing app to graph my data set and yours came out as one of the best looking+easy to modify! 

San
